import { Match } from "types/Match";
import { teamsInfo } from "./Teams";

export const dataDoneMatches: Match[] = [
  {
    team: teamsInfo.Arsenal,
    opponent: teamsInfo.Chelsea,
    result: "W",
    score: "2-0",
    location: "Emirates Stadium",
    time: "22:10",
    finished: true,
    date: "05/21/2024",
    minAge: 18,
    maxAge: 40,
    minPlayers: 11,
    maxPlayers: 18,
  },
  {
    team: teamsInfo.Arsenal,
    opponent: teamsInfo.Chelsea,
    result: "W",
    score: "2-0",
    location: "Emirates Stadium",
    time: "22:10",
    finished: true,
    date: "05/21/2024",
    minAge: 18,
    maxAge: 40,
    minPlayers: 11,
    maxPlayers: 18,
  },
  {
    team: teamsInfo.Arsenal,
    opponent: teamsInfo.Chelsea,
    result: "W",
    score: "2-0",
    location: "Emirates Stadium",
    time: "22:10",
    finished: true,
    date: "05/21/2024",
    minAge: 18,
    maxAge: 40,
    minPlayers: 11,
    maxPlayers: 18,
  },
  {
    team: teamsInfo.Arsenal,
    opponent: teamsInfo.Chelsea,
    result: "W",
    score: "2-0",
    location: "Emirates Stadium",
    time: "22:10",
    finished: true,
    date: "05/21/2024",
    minAge: 18,
    maxAge: 40,
    minPlayers: 11,
    maxPlayers: 18,
  },
];
