import { Player } from "types/Player";
import { teamsInfo } from "./Teams";

export const dataPlayers: Player[] = [
  {
    avatar: "/logo192.png",
    fullName: "First & Last Name",
    age: 20,
    nationality: "Vietnam",
    jerseyNumber: 10,
    position: "Forward",
    team: teamsInfo.Arsenal,
  },
  {
    avatar: "/logo192.png",
    fullName: "First & Last Name",
    age: 20,
    nationality: "Vietnam",
    jerseyNumber: 10,
    position: "WingBack",
    team: teamsInfo.Arsenal,
  },
  {
    avatar: "/logo192.png",
    fullName: "First & Last Name",
    age: 20,
    nationality: "Vietnam",
    jerseyNumber: 10,
    position: "Central Midfielder",
    team: teamsInfo.Arsenal,
  },
  {
    avatar: "/logo192.png",
    fullName: "First & Last Name",
    age: 20,
    nationality: "Vietnam",
    jerseyNumber: 10,
    position: "Defensive Midfielder",
    team: teamsInfo.Arsenal,
  },
  {
    avatar: "/logo192.png",
    fullName: "First & Last Name",
    age: 20,
    nationality: "Vietnam",
    jerseyNumber: 10,
    position: "Attacking Midfielder",
    team: teamsInfo.Arsenal,
  },
  {
    avatar: "/logo192.png",
    fullName: "First & Last Name",
    age: 20,
    nationality: "Vietnam",
    jerseyNumber: 10,
    position: "Winger",
    team: teamsInfo.Arsenal,
  },
  {
    avatar: "/logo192.png",
    fullName: "First & Last Name",
    age: 20,
    nationality: "Vietnam",
    jerseyNumber: 10,
    position: "CentreForward",
    team: teamsInfo.Arsenal,
  },
  {
    avatar: "/logo192.png",
    fullName: "First & Last Name",
    age: 20,
    nationality: "Vietnam",
    jerseyNumber: 10,
    position: "Forward",
    team: teamsInfo.Arsenal,
  },
  {
    avatar: "/logo192.png",
    fullName: "First & Last Name",
    age: 20,
    nationality: "Vietnam",
    jerseyNumber: 10,
    position: "Forward",
    team: teamsInfo.Arsenal,
  },
  {
    avatar: "/logo192.png",
    fullName: "First & Last Name",
    age: 20,
    nationality: "Vietnam",
    jerseyNumber: 10,
    position: "Forward",
    team: teamsInfo.Arsenal,
  },
  {
    avatar: "/logo192.png",
    fullName: "First & Last Name",
    age: 20,
    nationality: "Vietnam",
    jerseyNumber: 10,
    position: "Forward",
    team: teamsInfo.Arsenal,
  },
  {
    avatar: "/logo192.png",
    fullName: "First & Last Name",
    age: 20,
    nationality: "Vietnam",
    jerseyNumber: 10,
    position: "Forward",
    team: teamsInfo.Arsenal,
  },
  {
    avatar: "/logo192.png",
    fullName: "First & Last Name",
    age: 20,
    nationality: "Vietnam",
    jerseyNumber: 10,
    position: "Forward",
    team: teamsInfo.Arsenal,
  },
  {
    avatar: "/logo192.png",
    fullName: "First & Last Name",
    age: 20,
    nationality: "Vietnam",
    jerseyNumber: 10,
    position: "Forward",
    team: teamsInfo.Arsenal,
  },
  {
    avatar: "/logo192.png",
    fullName: "First & Last Name",
    age: 20,
    nationality: "Vietnam",
    jerseyNumber: 10,
    position: "Forward",
    team: teamsInfo.Arsenal,
  },
  {
    avatar: "/logo192.png",
    fullName: "First & Last Name",
    age: 20,
    nationality: "Vietnam",
    jerseyNumber: 10,
    position: "Forward",
    team: teamsInfo.Arsenal,
  },
  {
    avatar: "/logo192.png",
    fullName: "First & Last Name",
    age: 20,
    nationality: "Vietnam",
    jerseyNumber: 10,
    position: "Forward",
    team: teamsInfo.Arsenal,
  },
  {
    avatar: "/logo192.png",
    fullName: "First & Last Name",
    age: 20,
    nationality: "Vietnam",
    jerseyNumber: 10,
    position: "Forward",
    team: teamsInfo.Arsenal,
  },
];
