import { Match } from "types/Match";
import { teamsInfo } from "./Teams";

export const dataUpcomingMatches: Match[] = [
  {
    id: 4,
    team: teamsInfo.Arsenal,
    opponent: teamsInfo.Chelsea,
    result: "W",
    score: "2-0",
    location: "Emirates Stadium",
    time: "22:10",
    finished: false,
    date: "05/21/2024",
  },
  {
    id: 5,
    team: teamsInfo.Arsenal,
    opponent: teamsInfo.Chelsea,
    result: "W",
    score: "2-0",
    location: "Emirates Stadium",
    time: "22:10",
    finished: false,
    date: "05/21/2024",
  },
  {
    id: 6,
    team: teamsInfo.Arsenal,
    opponent: teamsInfo.Chelsea,
    result: "W",
    score: "2-0",
    location: "Emirates Stadium",
    time: "22:10",
    finished: false,
    date: "05/21/2024",
  },
  {
    id: 7,
    team: teamsInfo.Arsenal,
    opponent: teamsInfo.Chelsea,
    result: "W",
    score: "2-0",
    location: "Emirates Stadium",
    time: "22:10",
    finished: false,
    date: "05/21/2024",
  },
  {
    id: 8,
    team: teamsInfo.Arsenal,
    opponent: teamsInfo.Chelsea,
    result: "W",
    score: "2-0",
    location: "Emirates Stadium",
    time: "22:10",
    finished: false,
    date: "05/21/2024",
  },
  {
    id: 9,
    team: teamsInfo.Arsenal,
    opponent: teamsInfo.Chelsea,
    result: "W",
    score: "2-0",
    location: "Emirates Stadium",
    time: "22:10",
    finished: false,
    date: "05/21/2024",
  },
  {
    id: 10,
    team: teamsInfo.Arsenal,
    opponent: teamsInfo.Chelsea,
    result: "W",
    score: "2-0",
    location: "Emirates Stadium",
    time: "22:10",
    finished: false,
    date: "05/21/2024",
  },
  {
    id: 11,
    team: teamsInfo.Arsenal,
    opponent: teamsInfo.Chelsea,
    result: "W",
    score: "2-0",
    location: "Emirates Stadium",
    time: "22:10",
    finished: false,
    date: "05/23/2024",
  },
  {
    id: 12,
    team: teamsInfo.Arsenal,
    opponent: teamsInfo.Chelsea,
    result: "W",
    score: "2-0",
    location: "Emirates Stadium",
    time: "22:10",
    finished: false,
    date: "05/23/2024",
  },
  {
    id: 13,
    team: teamsInfo.Arsenal,
    opponent: teamsInfo.Chelsea,
    result: "W",
    score: "2-0",
    location: "Emirates Stadium",
    time: "22:10",
    finished: false,
    date: "05/24/2024",
  },
  {
    id: 14,
    team: teamsInfo.Arsenal,
    opponent: teamsInfo.Chelsea,
    result: "W",
    score: "2-0",
    location: "Emirates Stadium",
    time: "22:10",
    finished: false,
    date: "05/24/2024",
  },
];
