import { MatchesByDate } from "types";
import { Teams } from "./Teams";

export const dataUpcomingMatches: { [tournament: string]: MatchesByDate } = {
  "First Team": {
    "Saturday 11 May 2024": [
      {
        team: Teams.Arsenal,
        opponent: Teams.Chelsea,
        result: "W",
        score: "2-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: false,
        date: "2021-10-10",
      },
      {
        team: Teams.Arsenal,
        opponent: Teams.Chelsea,
        result: "W",
        score: "2-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: false,
        date: "2021-10-10",
      },
    ],
    "Tuesday 7 May 2024": [
      {
        team: Teams.Arsenal,
        opponent: Teams.Chelsea,
        result: "W",
        score: "2-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: false,
        date: "2021-10-10",
      },
      {
        team: Teams.Arsenal,
        opponent: Teams.Chelsea,
        result: "W",
        score: "2-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: false,
        date: "2021-10-10",
      },
    ],
  },
  PL2: {
    "Sunday 5 May 2024": [
      {
        team: Teams.Arsenal,
        opponent: Teams.Chelsea,
        result: "W",
        score: "2-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: false,
        date: "2021-10-10",
      },
      {
        team: Teams.Arsenal,
        opponent: Teams.Chelsea,
        result: "W",
        score: "2-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: false,
        date: "2021-10-10",
      },
    ],
  },
  U18: {
    "Friday 3 May 2024": [
      {
        team: Teams.Arsenal,
        opponent: Teams.Chelsea,
        result: "W",
        score: "2-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: false,
        date: "2021-10-10",
      },
      {
        team: Teams.Arsenal,
        opponent: Teams.Chelsea,
        result: "W",
        score: "2-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: false,
        date: "2021-10-10",
      },
    ],
    "Sunday 28 April 2024": [
      {
        team: Teams.Arsenal,
        opponent: Teams.Chelsea,
        result: "W",
        score: "2-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: false,
        date: "2021-10-10",
      },
      {
        team: Teams.Arsenal,
        opponent: Teams.Chelsea,
        result: "W",
        score: "2-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: false,
        date: "2021-10-10",
      },
    ],
  },
};
