import { teamsInfo } from "constants/Teams";
import { ITeamPerformance } from "../types/TeamPerformanceTypes";

console.log(teamsInfo);

export const dataLeaderboardTeams: ITeamPerformance[] = [
  {
    currentPosition: 1,
    team: teamsInfo.Arsenal,
    prevPosition: 1,
    matchesPlayed: 10,
    wins: 8,
    draws: 2,
    losses: 0,
    goalsFor: 20,
    goalsAgainst: 5,
    goalDifference: 15,
    points: 26,
    recentMatches: [
      {
        id: 0,
        team: teamsInfo.Arsenal,
        opponent: teamsInfo.Chelsea,
        result: "W",
        score: "2-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
      {
        id: 1,
        team: teamsInfo.Arsenal,
        opponent: teamsInfo.Chelsea,
        result: "D",
        score: "0-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
      {
        id: 2,
        team: teamsInfo.Arsenal,
        opponent: teamsInfo.Chelsea,
        result: "L",
        score: "0-2",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
      {
        id: 3,
        team: teamsInfo.Arsenal,
        opponent: teamsInfo.Chelsea,
        result: "W",
        score: "3-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
      {
        id: 4,
        team: teamsInfo.Arsenal,
        opponent: teamsInfo.Chelsea,
        result: "W",
        score: "3-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
    ],
    nextMatch: {
      id: 5,
      team: teamsInfo.Arsenal,
      opponent: teamsInfo.Chelsea,
      result: "W",
      score: "2-0",
      location: "Emirates Stadium",
      time: "22:10",
      date: "05/21/2024",
    },
  },
  {
    currentPosition: 2,
    team: teamsInfo.Chelsea,
    prevPosition: 2,
    matchesPlayed: 10,
    wins: 7,
    draws: 2,
    losses: 1,
    goalsFor: 15,
    goalsAgainst: 5,
    goalDifference: 10,
    points: 23,
    recentMatches: [
      {
        id: 0,
        team: teamsInfo.Chelsea,
        opponent: teamsInfo.Arsenal,
        result: "L",
        score: "0-2",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
      {
        id: 1,
        team: teamsInfo.Chelsea,
        opponent: teamsInfo.Arsenal,
        result: "D",
        score: "0-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
      {
        id: 2,
        team: teamsInfo.Chelsea,
        opponent: teamsInfo.Arsenal,
        result: "W",
        score: "2-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
      {
        id: 3,
        team: teamsInfo.Chelsea,
        opponent: teamsInfo.Arsenal,
        result: "L",
        score: "0-3",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
      {
        id: 4,
        team: teamsInfo.Chelsea,
        opponent: teamsInfo.Arsenal,
        result: "L",
        score: "0-3",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
    ],
    nextMatch: {
      id: 5,
      team: teamsInfo.Chelsea,
      opponent: teamsInfo.Arsenal,
      result: "W",
      score: "2-0",
      location: "Emirates Stadium",
      time: "22:10",
      date: "05/21/2024",
    },
  },

  {
    currentPosition: 3,
    team: teamsInfo.Liverpool,
    prevPosition: 3,
    matchesPlayed: 10,
    wins: 6,
    draws: 3,
    losses: 1,
    goalsFor: 15,
    goalsAgainst: 5,
    goalDifference: 10,
    points: 21,
    recentMatches: [
      {
        id: 0,
        team: teamsInfo.Liverpool,
        opponent: teamsInfo.Arsenal,
        result: "W",
        score: "2-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
      {
        id: 1,
        team: teamsInfo.Liverpool,
        opponent: teamsInfo.Arsenal,
        result: "D",
        score: "0-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
      {
        id: 2,
        team: teamsInfo.Liverpool,
        opponent: teamsInfo.Arsenal,
        result: "W",
        score: "2-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
      {
        id: 3,
        team: teamsInfo.Liverpool,
        opponent: teamsInfo.Arsenal,
        result: "L",
        score: "0-3",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
      {
        id: 4,
        team: teamsInfo.Liverpool,
        opponent: teamsInfo.Arsenal,
        result: "W",
        score: "3-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
    ],
    nextMatch: {
      id: 5,
      team: teamsInfo.Liverpool,
      opponent: teamsInfo.Arsenal,
      result: "W",
      score: "2-0",
      location: "Emirates Stadium",
      time: "22:10",
      date: "05/21/2024",
    },
  },
  {
    currentPosition: 4,
    team: teamsInfo["Manchester United"],
    prevPosition: 4,
    matchesPlayed: 10,
    wins: 5,
    draws: 3,
    losses: 2,
    goalsFor: 15,
    goalsAgainst: 5,
    goalDifference: 10,
    points: 18,
    recentMatches: [
      {
        id: 0,
        team: teamsInfo["Manchester United"],
        opponent: teamsInfo.Arsenal,
        result: "W",
        score: "2-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
      {
        id: 1,
        team: teamsInfo["Manchester United"],
        opponent: teamsInfo.Arsenal,
        result: "D",
        score: "0-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
      {
        id: 2,
        team: teamsInfo["Manchester United"],
        opponent: teamsInfo.Arsenal,
        result: "W",
        score: "2-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
      {
        id: 3,
        team: teamsInfo["Manchester United"],
        opponent: teamsInfo.Arsenal,
        result: "L",
        score: "0-3",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
      {
        id: 4,
        team: teamsInfo["Manchester United"],
        opponent: teamsInfo.Arsenal,
        result: "W",
        score: "3-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
    ],
    nextMatch: {
      id: 5,
      team: teamsInfo["Manchester United"],
      opponent: teamsInfo.Arsenal,
      result: "W",
      score: "2",
      location: "Emirates Stadium",
      time: "22:10",
      date: "05/21/2024",
    },
  },
  {
    currentPosition: 5,
    team: teamsInfo["Manchester City"],
    prevPosition: 5,
    matchesPlayed: 10,
    wins: 4,
    draws: 3,
    losses: 3,
    goalsFor: 15,
    goalsAgainst: 5,
    goalDifference: 10,
    points: 15,
    recentMatches: [
      {
        id: 0,
        team: teamsInfo["Manchester City"],
        opponent: teamsInfo.Arsenal,
        result: "W",
        score: "2-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
      {
        id: 1,
        team: teamsInfo["Manchester City"],
        opponent: teamsInfo.Arsenal,
        result: "D",
        score: "0-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
      {
        id: 2,
        team: teamsInfo["Manchester City"],
        opponent: teamsInfo.Arsenal,
        result: "W",
        score: "2-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
      {
        id: 3,
        team: teamsInfo["Manchester City"],
        opponent: teamsInfo.Arsenal,
        result: "L",
        score: "0-3",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
      {
        id: 4,
        team: teamsInfo["Manchester City"],
        opponent: teamsInfo.Arsenal,
        result: "W",
        score: "3-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
    ],
    nextMatch: {
      id: 5,
      team: teamsInfo["Manchester City"],
      opponent: teamsInfo.Arsenal,
      result: "W",
      score: "2-0",
      location: "Emirates Stadium",
      time: "22:10",
      date: "05/21/2024",
    },
  },
  {
    currentPosition: 6,
    team: teamsInfo["Tottenham Hotspur"],
    prevPosition: 6,
    matchesPlayed: 10,
    wins: 3,
    draws: 3,
    losses: 4,
    goalsFor: 15,
    goalsAgainst: 5,
    goalDifference: 10,
    points: 12,
    recentMatches: [
      {
        id: 0,
        team: teamsInfo["Tottenham Hotspur"],
        opponent: teamsInfo.Arsenal,
        result: "W",
        score: "2-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
      {
        id: 1,
        team: teamsInfo["Tottenham Hotspur"],
        opponent: teamsInfo.Arsenal,
        result: "D",
        score: "0-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
      {
        id: 2,
        team: teamsInfo["Tottenham Hotspur"],
        opponent: teamsInfo.Arsenal,
        result: "W",
        score: "2-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
      {
        id: 3,
        team: teamsInfo["Tottenham Hotspur"],
        opponent: teamsInfo.Arsenal,
        result: "L",
        score: "0-3",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
      {
        id: 4,
        team: teamsInfo["Tottenham Hotspur"],
        opponent: teamsInfo.Arsenal,
        result: "W",
        score: "3-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
    ],
    nextMatch: {
      id: 5,
      team: teamsInfo["Tottenham Hotspur"],
      opponent: teamsInfo.Arsenal,
      result: "W",
      score: "2-0",
      location: "Emirates Stadium",
      time: "22:10",
      date: "05/21/2024",
    },
  },
  {
    currentPosition: 7,
    team: teamsInfo.Everton,
    prevPosition: 7,
    matchesPlayed: 10,
    wins: 2,
    draws: 3,
    losses: 5,
    goalsFor: 15,
    goalsAgainst: 5,
    goalDifference: 10,
    points: 9,
    recentMatches: [
      {
        id: 0,
        team: teamsInfo.Everton,
        opponent: teamsInfo.Arsenal,
        result: "W",
        score: "2-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
      {
        id: 1,
        team: teamsInfo.Everton,
        opponent: teamsInfo.Arsenal,
        result: "D",
        score: "0-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
      {
        id: 2,
        team: teamsInfo.Everton,
        opponent: teamsInfo.Arsenal,
        result: "W",
        score: "2-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
      {
        id: 3,
        team: teamsInfo.Everton,
        opponent: teamsInfo.Arsenal,
        result: "L",
        score: "0-3",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
      {
        id: 4,
        team: teamsInfo.Everton,
        opponent: teamsInfo.Arsenal,
        result: "W",
        score: "3-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
    ],
    nextMatch: {
      id: 5,
      team: teamsInfo.Everton,
      opponent: teamsInfo.Arsenal,
      result: "W",
      score: "2-0",
      location: "Emirates Stadium",
      time: "22:10",
      date: "05/21/2024",
    },
  },

  {
    currentPosition: 8,
    team: teamsInfo["Leicester City"],
    prevPosition: 8,
    matchesPlayed: 10,
    wins: 1,
    draws: 3,
    losses: 6,
    goalsFor: 15,
    goalsAgainst: 5,
    goalDifference: 10,
    points: 6,
    recentMatches: [
      {
        id: 0,
        team: teamsInfo["Leicester City"],
        opponent: teamsInfo.Arsenal,
        result: "W",
        score: "2-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
      {
        id: 1,
        team: teamsInfo["Leicester City"],
        opponent: teamsInfo.Arsenal,
        result: "D",
        score: "0-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
      {
        id: 2,
        team: teamsInfo["Leicester City"],
        opponent: teamsInfo.Arsenal,
        result: "W",
        score: "2-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
      {
        id: 3,
        team: teamsInfo["Leicester City"],
        opponent: teamsInfo.Arsenal,
        result: "L",
        score: "0-3",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
      {
        id: 4,
        team: teamsInfo["Leicester City"],
        opponent: teamsInfo.Arsenal,
        result: "W",
        score: "3-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
    ],
    nextMatch: {
      id: 5,
      team: teamsInfo["Leicester City"],
      opponent: teamsInfo.Arsenal,
      result: "W",
      score: "2-0",
      location: "Emirates Stadium",
      time: "22:10",
      date: "05/21/2024",
    },
  },
  {
    currentPosition: 9,
    team: teamsInfo["West Ham United"],
    prevPosition: 9,
    matchesPlayed: 10,
    wins: 0,
    draws: 3,
    losses: 7,
    goalsFor: 15,
    goalsAgainst: 5,
    goalDifference: 10,
    points: 3,
    recentMatches: [
      {
        id: 0,
        team: teamsInfo["West Ham United"],
        opponent: teamsInfo.Arsenal,
        result: "W",
        score: "2-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
      {
        id: 1,
        team: teamsInfo["West Ham United"],
        opponent: teamsInfo.Arsenal,
        result: "D",
        score: "0-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
      {
        id: 2,
        team: teamsInfo["West Ham United"],
        opponent: teamsInfo.Arsenal,
        result: "W",
        score: "2-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
      {
        id: 3,
        team: teamsInfo["West Ham United"],
        opponent: teamsInfo.Arsenal,
        result: "L",
        score: "0-3",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
      {
        id: 4,
        team: teamsInfo["West Ham United"],
        opponent: teamsInfo.Arsenal,
        result: "W",
        score: "3-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
    ],
    nextMatch: {
      id: 5,
      team: teamsInfo["West Ham United"],
      opponent: teamsInfo.Arsenal,
      result: "W",
      score: "2-0",
      location: "Emirates Stadium",
      time: "22:10",
      date: "05/21/2024",
    },
  },
  {
    currentPosition: 10,
    team: teamsInfo["Aston Villa"],
    prevPosition: 10,
    matchesPlayed: 10,
    wins: 0,
    draws: 3,
    losses: 7,
    goalsFor: 15,
    goalsAgainst: 5,
    goalDifference: 10,
    points: 3,
    recentMatches: [
      {
        id: 0,
        team: teamsInfo["Aston Villa"],
        opponent: teamsInfo.Arsenal,
        result: "W",
        score: "2-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
      {
        id: 1,
        team: teamsInfo["Aston Villa"],
        opponent: teamsInfo.Arsenal,
        result: "D",
        score: "0-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
      {
        id: 2,
        team: teamsInfo["Aston Villa"],
        opponent: teamsInfo.Arsenal,
        result: "W",
        score: "2-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
      {
        id: 3,
        team: teamsInfo["Aston Villa"],
        opponent: teamsInfo.Arsenal,
        result: "L",
        score: "0-3",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
      {
        id: 4,
        team: teamsInfo["Aston Villa"],
        opponent: teamsInfo.Arsenal,
        result: "W",
        score: "3-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
    ],
    nextMatch: {
      id: 5,
      team: teamsInfo["Aston Villa"],
      opponent: teamsInfo.Arsenal,
      result: "W",
      score: "2-0",
      location: "Emirates Stadium",
      time: "22:10",
      date: "05/21/2024",
    },
  },
];
