import { teamsInfo } from "constants/Teams";
import { ITeamPerformance } from "../types/TeamPerformanceTypes";

export const dataLeaderboardTeams: ITeamPerformance[] = [
  {
    currentPosition: 1,
    team: teamsInfo.Arsenal,
    prevPosition: 1,
    matchesPlayed: 10,
    wins: 8,
    draws: 2,
    losses: 0,
    goalsFor: 20,
    goalsAgainst: 5,
    goalDifference: 15,
    points: 26,
    recentMatches: [
      {
        team: teamsInfo.Arsenal,
        opponent: teamsInfo.Chelsea,
        result: "W",
        score: "2-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
      {
        team: teamsInfo.Arsenal,
        opponent: teamsInfo.Chelsea,
        result: "D",
        score: "0-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
      {
        team: teamsInfo.Arsenal,
        opponent: teamsInfo.Chelsea,
        result: "L",
        score: "0-2",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
      {
        team: teamsInfo.Arsenal,
        opponent: teamsInfo.Chelsea,
        result: "W",
        score: "3-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
      {
        team: teamsInfo.Arsenal,
        opponent: teamsInfo.Chelsea,
        result: "W",
        score: "3-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
    ],
    nextMatch: {
      team: teamsInfo.Arsenal,
      opponent: teamsInfo.Chelsea,
      result: "W",
      score: "2-0",
      location: "Emirates Stadium",
      time: "22:10",
      date: "05/21/2024",
    },
  },
  {
    currentPosition: 2,
    team: teamsInfo.Chelsea,
    prevPosition: 2,
    matchesPlayed: 10,
    wins: 7,
    draws: 2,
    losses: 1,
    goalsFor: 15,
    goalsAgainst: 5,
    goalDifference: 10,
    points: 23,
    recentMatches: [
      {
        team: teamsInfo.Chelsea,
        opponent: teamsInfo.Arsenal,
        result: "L",
        score: "0-2",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
      {
        team: teamsInfo.Chelsea,
        opponent: teamsInfo.Arsenal,
        result: "D",
        score: "0-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
      {
        team: teamsInfo.Chelsea,
        opponent: teamsInfo.Arsenal,
        result: "W",
        score: "2-0",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
      {
        team: teamsInfo.Chelsea,
        opponent: teamsInfo.Arsenal,
        result: "L",
        score: "0-3",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
      {
        team: teamsInfo.Chelsea,
        opponent: teamsInfo.Arsenal,
        result: "L",
        score: "0-3",
        location: "Emirates Stadium",
        time: "22:10",
        finished: true,
        date: "05/21/2024",
      },
    ],
    nextMatch: {
      team: teamsInfo.Chelsea,
      opponent: teamsInfo.Arsenal,
      result: "W",
      score: "2-0",
      location: "Emirates Stadium",
      time: "22:10",
      date: "05/21/2024",
    },
  },
];
